# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  rabbitmq1:
    image: rabbitmq:3.10-management-alpine
    container_name: rabbitmq1
    hostname: rabbitmq1
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_ERLANG_COOKIE=secret
      - CLUSTERED=true
    ports:
      - "5672:5672"
      - "8085:15672"
    networks:
      - my-networks
      
  rabbitmq2:
    image: rabbitmq:3.10-management-alpine
    container_name: rabbitmq2
    hostname: rabbitmq2
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_ERLANG_COOKIE=secret
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq1
      - RAM_NODE=true
    ports:
      - "5673:5672"
      - "8086:15672"
    networks:
      - my-networks
    links:
      - rabbitmq1

  rabbitmq3:
    image: rabbitmq:3.10-management-alpine
    container_name: rabbitmq3
    hostname: rabbitmq3
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_ERLANG_COOKIE=secret
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq1
    ports:
      - "5674:5672"
      - "8087:15672"
    networks:
      - my-networks   
    links:
      - rabbitmq1
      - rabbitmq2

networks:
  my-networks:
    driver: bridge