version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fornecedor
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"