
server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          default-label: microservice-repo
          search-paths: fornecedor  
          uri: https://github.com/Bodegami/poc-spring-cloud-configs
          username: ${GITHUB_USER}
          password: ${GITHUB_TOKEN}
  
  
#spring:
#  profiles:
#    active: native  
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: c:/microservice-repo